import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })


export const metadata = {
  title: 'Tathagata Nandi Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/assets/download.png'/>
      </head>
      <body className={`${inter.className} ${montserrat.className}`}>{children}</body> 
    </html>
  )
}
